### ISSUE TITLE
Cipher doFinal gives null dereference when input bytes are missing

### ISSUE THREAD

**Issue by bauer-matthews** [corretto/amazon-corretto-crypto-provider#143]
Cipher doFinal gives null dereference when input bytes are missing. Below is a simple test case to demonstrate the issue. With the SunJCE provider (openJDK 11) no exception is raised and the returned byte array is all zeros.  

```
    @Test
    public void cipherNoInputCorretto() throws NoSuchAlgorithmException, NoSuchPaddingException,
            InvalidKeyException, IllegalBlockSizeException, BadPaddingException, NoSuchProviderException {

        com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider.install();

        KeyPairGenerator keygen = KeyPairGenerator.getInstance("RSA");
        keygen.initialize(2048);
        Key key = keygen.generateKeyPair().getPublic();

        Cipher cipher = Cipher.getInstance("RSA/ECB/NoPadding", "AmazonCorrettoCryptoProvider");
        cipher.init(Cipher.ENCRYPT_MODE, key);
        cipher.doFinal();
    }
```

**Comment by SalusaSecondus** [comment]
Thank you for this report. I do see that we have a `NullPointerException` in this case and that should be fixed.

----
My repro.

```
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.lang.System.arraycopy(Native Method)
        at com.amazon.corretto.crypto.provider.RsaCipher.engineDoFinal(RsaCipher.java:195)
        at com.amazon.corretto.crypto.provider.RsaCipher.engineDoFinal(RsaCipher.java:148)
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2085)
        at CipherNoInputCorretto.main(CipherNoInputCorretto.java:14)
```

**Comment by alex-chew** [comment]
Closing as this will be fixed in the upcoming release.
