### ISSUE TITLE
Cipher init does not validate key argument

### ISSUE THREAD

**Issue by bauer-matthews** [corretto/amazon-corretto-crypto-provider#144]
A call to Cipher init should validate that the `key` argument is not null. This is done for RSA Cipher instances but not for AES/GCM cipher instances.  Below is a simple test case to reproduce the issue. 

```
    @Test(expectedExceptions = {InvalidKeyException.class, IllegalArgumentException.class})
    public void cipherInitNullKeyCorretto() throws NoSuchAlgorithmException, NoSuchPaddingException,
            NoSuchProviderException, InvalidKeyException {

        com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider.install();

        Random rand = new Random();
        byte[] input = new byte[128];
        rand.nextBytes(input);

        Key key = null;

        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding", "AmazonCorrettoCryptoProvider");
        cipher.init(Cipher.ENCRYPT_MODE, key); // This should throw InvalidKeyException or IllegalArgumentException
        cipher.update(input);
    }
```

**Comment by SalusaSecondus** [comment]
I see that `NullPointerException` and this is definitely something we should fix. Thank you for the report.

```
Exception in thread "main" java.lang.NullPointerException: Null array passed
        at com.amazon.corretto.crypto.provider.AesGcmSpi.encryptInit(Native Method)
        at com.amazon.corretto.crypto.provider.AesGcmSpi.lazyInit(AesGcmSpi.java:888)
        at com.amazon.corretto.crypto.provider.AesGcmSpi.engineUpdate(AesGcmSpi.java:427)
        at com.amazon.corretto.crypto.provider.AesGcmSpi.engineUpdate(AesGcmSpi.java:399)
        at java.base/javax.crypto.Cipher.update(Cipher.java:1829)
        at CipherInitNullKeyCorretto.main(CipherInitNullKeyCorretto.java:14)
```

**Comment by alex-chew** [comment]
Closing as this will be fixed in the upcoming release.
