### ISSUE TITLE
Algorithm Name Case Sensitivity?

### ISSUE THREAD

**Issue by hybby** [corretto/amazon-corretto-crypto-provider#76]
Hello,

We've recently tried to drop Amazon Corretto Crypto Providers into one of our applications that was previously using SunEC quite happily.   We're using [corretto-8](https://github.com/corretto/corretto-8) with it and have configured our application to use the custom security providers using the `-Djava.security.properties=/path/to/amazon-corretto-crypto-provider.security` option where the file is the one you specify.

This application is a third-party product that we don't have visibility of the code of.  At a high level, we are configuring it to use the `SHA256withECDSA` algorithm to sign and verify access tokens.

The snippet we've obtained from debug logging is as follows:

```
org.forgerock.openam.oauth2.token.OAuth2JwtTokenHelper:12/19/2019 05:36:02:381 PM UTC: Thread[http-apr-8443-exec-10,5,main]: TransactionId[3dcad83d-99a8-49a1-ad06-c0167f5be808-160]
Unable to verify JWT with handler org.forgerock.json.jose.jws.handlers.HmacSigningHandler@420cfdc0: {}
org.forgerock.json.jose.exceptions.JwsSigningException: Unsupported Signing Algorithm, SHA256WithECDSA
```

```
Caused by: java.security.NoSuchAlgorithmException: Algorithm SHA256WithECDSA not available
```

The second error message made me think - are algorithm names provided by Amazon Corretto Crypto Provider case sensitive or not?  The algorithm `SHA256withECDSA` is quite clearly supported from the README, but I'm not certain what would happen when `SHA256WithECDSA` is specified instead.

I've had a look at the [standard names](https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html) documentation from Oracle and they specify that names are not case-sensitive.

> Note: Standard names are not case-sensitive.

We've confirmed that falling back to SunEC causes the same application to work again immediately.  Only when we specify that AmazonCorrettoCryptoProvider should be used do we see the issue.

I wonder if you could confirm whether you think specifying `SHA256WithECDSA` as an algorithm _should_ work.

Apologies if this issue is a bit fuzzy; I've tried to give all of the information I have at the moment for what seems to be quite an opaque bug that we're experiencing..

**Comment by scottarc** [comment]
This issue was thrown by `org.forgerock.json.jose.jws.handlers.HmacSigningHandler@420cfdc0`.

`HmacSigningHandler` in `org.forgerock.json.jose.jws.handlers` is looking for a hash function (SHA256), not a signature algorithm (ECDSA with SHA256). 

Case sensitivity *might* be a rabbit hole. Please check that you're using [`ECDSASigningHander`](https://github.com/WrenSecurity/forgerock-json-web-token/blob/master/src/main/java/org/forgerock/json/jose/jws/handlers/ECDSASigningHandler.java) in the code that consumes Forgerock JWT and ACCP.

ACCP isn't doing anything to introduce case sensitivity where it doesn't already exist ([for reference](https://github.com/corretto/amazon-corretto-crypto-provider/blob/b204b018f6aa5d42b4fee0d0a94a93994bede081/src/com/amazon/corretto/crypto/provider/AmazonCorrettoCryptoProvider.java#L122-L235)).

If case sensitivity does matter, ACCP is using the lowercase `w` ([source excerpt](https://github.com/corretto/amazon-corretto-crypto-provider/blob/b204b018f6aa5d42b4fee0d0a94a93994bede081/src/com/amazon/corretto/crypto/provider/AmazonCorrettoCryptoProvider.java#L92-L106); this means `SHA256withECDSA` would be selected in a case-sensitive world, not `SHA256WithECDSA`).

**Comment by SalusaSecondus** [comment]
As @scottarc noted, ACCP should not be case-sensitive.

Could you please share a full stack-trace with us and links to the relevant code (if possible)?

**Comment by hybby** [comment]
Hello @scottarc, @SalusaSecondus - thank you for your swift reply to my question.
It's not possible for me to share links to any relevant code - the product that we're using is ForgeRock Access Management (AM) 6.1.  This is a custom version whose closest analogue is 6.0.0.7 with some backported patches from later versions (6.5+)  The code to this product isn't readily available, as the software is provided to us by our vendor.  Apologies, and I understand if it's not possible for you to work much further without visibility of the code.

Thanks for your insight around `org.forgerock.json.jose.jws.handlers.HmacSigningHandler` being used instead of `org.forgerock.json.jose.jws.handlers.ECDSASigningHandler` - this does seem to be relevant and suspicious, but it does seem strange that reverting back to SunEC causes the failing behaviour to succeed again.  The request that we're making is to the `/oauth2/tokeninfo` endpoint of the OpenAM service which again, I don't have the ability to see or share the code of.

Please find below a full stack trace of which I provided excerpts of previously, in case it helps:

```
org.forgerock.openam.oauth2.token.OAuth2JwtTokenHelper:12/19/2019 05:36:02:381 PM UTC: Thread[http-apr-8443-exec-10,5,main]: TransactionId[3dcad83d-99a8-49a1-ad06-c0167f5be808-160]
Unable to verify JWT with handler org.forgerock.json.jose.jws.handlers.HmacSigningHandler@420cfdc0: {}
org.forgerock.json.jose.exceptions.JwsSigningException: Unsupported Signing Algorithm, SHA256WithECDSA
	at org.forgerock.json.jose.jws.handlers.HmacSigningHandler.signWithHMAC(HmacSigningHandler.java:73)
	at org.forgerock.json.jose.jws.handlers.HmacSigningHandler.verify(HmacSigningHandler.java:96)
	at org.forgerock.json.jose.jws.SignedJwt.verify(SignedJwt.java:194)
	at org.forgerock.openam.oauth2.token.OAuth2JwtTokenHelper.tryVerify(OAuth2JwtTokenHelper.java:241)
	at org.forgerock.openam.oauth2.token.OAuth2JwtTokenHelper.lambda$hasValidSignature$2(OAuth2JwtTokenHelper.java:236)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
	at org.forgerock.openam.oauth2.token.OAuth2JwtTokenHelper.hasValidSignature(OAuth2JwtTokenHelper.java:236)
	at org.forgerock.openam.oauth2.token.stateless.StatelessTokenHelper.verifySignature(StatelessTokenHelper.java:472)
	at org.forgerock.openam.oauth2.token.stateless.StatelessTokenHelper.readAccessToken(StatelessTokenHelper.java:180)
	at org.forgerock.openam.oauth2.token.stateless.StatelessTokenStore.readAccessToken(StatelessTokenStore.java:280)
	at org.forgerock.openam.oauth2.token.OpenAMTokenStore.readAccessToken(OpenAMTokenStore.java:151)
	at org.forgerock.openam.oauth2.token.TokenStore.readAccessToken(TokenStore.java:226)
	at org.forgerock.oauth2.core.AccessTokenVerifier.verify(AccessTokenVerifier.java:104)
	at org.forgerock.oauth2.core.AccessTokenVerifier.verify(AccessTokenVerifier.java:72)
	at org.forgerock.oauth2.core.TokenInfoService.getTokenInfo(TokenInfoService.java:81)
	at org.forgerock.oauth2.restlet.ValidationServerResource.validate(ValidationServerResource.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:511)
	at org.restlet.resource.ServerResource.get(ServerResource.java:723)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:603)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:662)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:348)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1020)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.forgerock.openam.rest.service.RestletRealmRouter.doHandle(RestletRealmRouter.java:94)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:77)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:641)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at org.forgerock.openam.rest.RestEndpointServlet$RestletHandler.handle(RestEndpointServlet.java:183)
	at org.forgerock.http.handler.Handlers$UndescribedAsDescribableHandler.handle(Handlers.java:179)
	at org.forgerock.openam.dpro.session.ProofOfPossessionTokenFilter.filter(ProofOfPossessionTokenFilter.java:88)
	at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:53)
	at org.forgerock.http.filter.TransactionIdInboundFilter.filter(TransactionIdInboundFilter.java:75)
	at org.forgerock.http.handler.Handlers$1.handle(Handlers.java:53)
	at org.forgerock.http.servlet.HttpFrameworkServlet.service(HttpFrameworkServlet.java:254)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.forgerock.openam.rest.RestEndpointServlet$HttpServletWrapper.service(RestEndpointServlet.java:254)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.forgerock.openam.rest.RestEndpointServlet.service(RestEndpointServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.forgerock.openam.validation.ResponseValidationFilter.doFilter(ResponseValidationFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.forgerock.openam.headers.SetHeadersFilter.doFilter(SetHeadersFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:112)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.forgerock.openam.audit.context.AuditContextFilter.doFilter(AuditContextFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2486)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.NoSuchAlgorithmException: Algorithm SHA256WithECDSA not available
	at javax.crypto.Mac.getInstance(Mac.java:181)
	at org.forgerock.json.jose.jws.handlers.HmacSigningHandler.signWithHMAC(HmacSigningHandler.java:68)
	... 114 more
```

**Comment by SalusaSecondus** [comment]
Looking at the end of your stacktrace, we can see that @scottarc is correct about the cause. For some reason the `HmacSigningHandler` is being asked to use the `SHA256WithECDSA` algorithm. This won't work regardless the providers installed.
```
Caused by: java.security.NoSuchAlgorithmException: Algorithm SHA256WithECDSA not available
	at javax.crypto.Mac.getInstance(Mac.java:181)
	at org.forgerock.json.jose.jws.handlers.HmacSigningHandler.signWithHMAC(HmacSigningHandler.java:68)
```

I think the real question is "Why does this ever work?" Something other than just provider configuration is changing. Unfortunately, without actually having access to your software, I don't think we can help you identify what changed or why.

**Comment by hybby** [comment]
@SalusaSecondus - thanks for your continued help.  I agree with your assessment.  It does appear that the software is behaving in an unexpected way here and we've raised a support case with our vendor to help further troubleshoot the issue.  

Thank you for your time so far.  I'll close this issue as it does not seem to be an issue with ACCP.

**Comment by SalusaSecondus** [comment]
Please be sure to let us know if ACCP behavior (even if correct) was involved causing this. We like to understand all the interactions of our library.

**Comment by NetYaroze** [comment]
@SalusaSecondus 

Raising for some visibility if any other customers stumble across this, but yeah, it is our signing handler. https://bugster.forgerock.org/jira/browse/COMMONS-532
